local: https://raw.githubusercontent.com/pine64/OpenPineBuds/533d01aee617f24dfe9cda124fbb20b6efbe2f73/platform/Makefile
remote: https://raw.githubusercontent.com/OneDeuxTriSeiGo/device_soc_bestechnic/c0502a1345f2f5b7ffc7f38b5374be0fcb42a487/bes2600/liteos_m/sdk/bsp/platform/Makefile
diff -sw local remote
---

0a1,15
> # Copyright (c) 2021 Bestechnic (Shanghai) Co., Ltd. All rights reserved.
> # Licensed under the Apache License, Version 2.0 (the "License");
> # you may not use this file except in compliance with the License.
> # You may obtain a copy of the License at
> #
> #     http://www.apache.org/licenses/LICENSE-2.0
> #
> # Unless required by applicable law or agreed to in writing, software
> # distributed under the License is distributed on an "AS IS" BASIS,
> # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
> # See the License for the specific language governing permissions and
> # limitations under the License.
> cur_dir := $(dir $(lastword $(MAKEFILE_LIST)))
> 
> 
3a19
> ifneq ($(WIFI_RAMRUN),1)
5a22,26
> endif
> 
> ifeq ($(BECO),1)
> obj-y += beco/
> endif
7c28
< subdir-ccflags-y += -Iplatform/cmsis/inc -Iplatform/hal -Iutils/hwtimer_list
---
> subdir-ccflags-y += -Iplatform/cmsis/inc -Iplatform/hal -Iutils/hwtimer_list -Iplatform/drivers/wifi/$(CHIP)
