local: https://raw.githubusercontent.com/pine64/OpenPineBuds/29b195e12da6a5c791d1418af8448be80bccf18d/platform/cmsis/DSP_Lib/BasicMathFunctions/Makefile
remote: https://raw.githubusercontent.com/ARM-software/CMSIS-DSP/58cda4700284fdbb26201d960089a6ca4b04523e/Source/BasicMathFunctions/Makefile
diff -sw local remote
---

1,6d0
< cur_dir := $(dir $(lastword $(MAKEFILE_LIST)))
< 
< obj-y := $(patsubst $(cur_dir)%,%,$(wildcard $(cur_dir)*.c $(cur_dir)*.S))
< obj-y := $(filter-out %Functions.c,$(obj-y))
< obj-y := $(obj-y:.c=.o)
< obj-y := $(obj-y:.S=.o)
